.Dd October 23, 2017
.Dt LUMINA-MEDIAPLAYER 8
.Os 1.3.3

.Sh NAME
.Nm lumina-mediaplayer
.Nd is a simple graphical utility that plays various media files. It also has hooks
to stream online radio services.

.Sh SYNOPSIS
.Nm
.Op <FileName1 FileName2  ... >
.Nm
.Op <argument>

.Sh DESCRIPTION
.Nm
opens up the graphical interface for the media player. The user can sync a Pandora account
and stream music. The user can also create and manage a playlist of media files from their system.
.Pp
The command can take multiple file names at a time and add them into a playlist. It can
open .mp3, .mp4, .flac, .acc, .mpeg2, and mpeg4 files.
Other than using the gui, the user is able to add a song by specifying a file name
or multiple file names.
.Pp
.Nm
has one optional argument, and it simply opens up the interface on the Pandora account page.
.Bl -tag -width indent
.It Ic --pandora
Opens the interface on the Pandora account page.

.Sh EXAMPLES

.Bl -tag -width indent
.It lumina-mediaplayer Downloads/Testing.mp3
Opens the interface and adds Testing.mp3 into the playlist.
.It lumina-mediaplayer Downloads/Testing.mp3 Testing2.mp4 Testing 3.mp3
Opens the interface and adds Testing.mp3, Testing2.mp4, and
Testing 3.mp3 into the playlist.
.It lumina-mediaplayer --pandora
Opens the interface on the Pandora account page.

.Sh AUTHORS
.An Aaron St. John
.Aq aaron@ixsystems.com
