.Dd October 27, 2017
.Dt LUMINA-SEARCH 8
.Os  1.3.3

.Sh NAME
.Nm lumina-search
.Nd is a simple graphical utility to search for files and applications on the system.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
brings up the graphical utility to search the system. There are two search filters
to chose from: "Applications" and "Files or Directories". The utility will search the
system depending on the selected filter. Search results populate a list with
the most relevant options first.

.Sh AUTHORS
.An Aaron St. John
.Aq aaron@ixsystems.com
