.Dd October 20, 2017
.Dt LUMINA-TEXTEDIT 8
.Os 1.3.3

.Sh NAME
.Nm lumina-textedit
.Nd is a plaintext editor.

.Sh SYNOPSIS
.Nm
.Op <new file name>
.Pp
.Nm
.Op <existing file name>

.Sh DESCRIPTION
The
.Nm
is a plaintext editor with syntax highlighting, tabs, and find/replace functionality.
.Pp
The user can specify either a new file name or an existing file name.

.Bl -tag -width indent
.It \fBNew File Test \fR
Opens a new file in the text editor named "New File Test".
.It \fBexisting file\fR
Opens the specified existing file in the text editor.
