.Dd November 3, 2017
.Dt LUMINA-CONFIG 8
.Os 1.3.3

.Sh NAME
.Nm lumina-config
.Nd used to modify different desktop settings.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
opens the graphical utility to modify many different desktop settings.
Settings include appearance, desktop defaults, interface
configuration, system settings, and user settings.

.Sh FILES
.Bl -tag -indent width
.It Pa /usr/local/bin/lumina-config
.El

.Sh AUTHORS
.An Aaron St. John
.Aq aaron@ixsystems.com
